#ifndef __MAIN_H__
#define __MAIN_H__

#include <stdio.h>

//Generated by cmake using buildInfo.h template
#include "buildInfo.h"

//don't give warnings for external stuff that can't be controlled
#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-function"
#pragma clang diagnostic ignored "-Wunused-parameter"
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wmissing-field-initializers"
#elif defined(__GNUC__) || defined(__MINGW32__) //gcc
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-function"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#elif defined(_MSC_VER) //msvc
//(defined last, becasue sometimes when using clang with msvc, this will also be defined even tho
//we're getting clang errors/warnings)
#pragma warning(push, 0)
#endif

#include "raylib.h"

#define RAYGUI_IMPLEMENTATION
#define RAYGUI_SUPPORT_ICONS
#include "raygui.h"
#undef RAYGUI_IMPLEMENTATION // Avoid including raygui implementation again

#include "ricons.h"

#ifdef _MSC_VER
#pragma warning(pop)
#elif defined(__GNUC__) || defined(__MINGW32__) //gcc
#pragma GCC diagnostic pop
#elif defined(__clang__)
#pragma clang diagnostic pop
#endif

int main(void);

typedef char Fixed256String[255];

typedef struct UIState
{
    int dropdownBox000Active;
    bool dropDown000EditMode;

    int dropdownBox001Active;
    bool dropDown001EditMode;

    int spinner001Value;
    bool spinnerEditMode;

    int valueBox002Value;
    bool valueBoxEditMode;

    char textBoxText[64];
    bool textBoxEditMode;

    int listViewScrollIndex;
    int listViewActive;

    int listViewExScrollIndex;
    int listViewExActive;
    int listViewExFocus;
    Fixed256String listViewExList[8];

    char multiTextBoxText[141];
    bool multiTextBoxEditMode;
    Color colorPickerValue;

    int sliderValue;
    int sliderBarValue;
    float progressValue;

    bool forceSquaredChecked;

    float alphaValue;

    int comboBoxActive;

    int toggleGroupActive;

    Vector2 viewScroll;
    //----------------------------------------------------------------------------------

    // Custom GUI font loading
    Font font;

    bool exitWindow;
    bool showMessageBox;

    char textInput[256];
    bool showTextInputBox;

    char textInputFileName[256];
} UIState;

void initUI(UIState *state);
void drawUI(UIState *state);

#endif