#include "enttTest.h"

//Generated by cmake using buildInfo.h.in template
#include "buildInfo.h"
#define BLISS_FULL_HEADER BLISS_TITLE " " BLISS_VERSION

#include "DevUI.h"

#include "main.h"

int main(void)
{
    tryEntt();

    unsigned int screenWidth = 800;
    unsigned int screenHeight = 600;

    printf("Starting " BLISS_FULL_HEADER "...\n");
    InitWindow(screenWidth, screenHeight, BLISS_FULL_HEADER);

    Font fontRobotoMono = LoadFontEx("resources/fonts/RobotoMono-Regular.ttf", 28, 0, 255);
    Font fontRobotoMonoSm = LoadFontEx("resources/fonts/RobotoMono-Regular.ttf", 12, 0, 255);
    Font font = LoadFontEx("resources/fonts/Merriweather-Regular.ttf", 14, 0, 255);

    SetTargetFPS(60);

    DevUIState devUIState;
    DevUIInit(&devUIState, GetGLFWwindowHandle());

    Texture2D santaTex = LoadTexture("resources/santa/Idle (1).png");

    bool exitWindow = false;
    while (!exitWindow)
    {
        exitWindow = WindowShouldClose();

        // Update
        //----------------------------------------------------------------------------------
        BeginDrawing();
        DevUINewFrame();
        ClearBackground(WHITE);

        if (!devUIState.igIO->WantCaptureMouse)
        {
            //only take mouse input in the game if imgui isn't catching it
            //clicks and input shouldn't go through a window
        }
        if (!devUIState.igIO->WantCaptureKeyboard)
        {
            //check keyboard inputs
        }
        if (!devUIState.igIO->WantTextInput)
        {
            //for on mobile & consoles
        }

        DrawTexture(santaTex,
                    screenWidth / 2 - santaTex.width / 2,
                    screenHeight / 2 - santaTex.height / 2, WHITE);

        Vector2 textDim = MeasureTextEx(fontRobotoMono, BLISS_FULL_HEADER,
                                        (float)fontRobotoMono.baseSize, 0);
        Vector2 textPos;
        textPos.x = (screenWidth - textDim.x) / 2.0f;
        textPos.y = (screenHeight - textDim.y) / 2.0f;

        DrawTextEx(fontRobotoMono, BLISS_FULL_HEADER, textPos,
                   (float)fontRobotoMono.baseSize, 0, DARKGRAY);

        //----------------------------------------------------------------------------------

        rlglDraw(); //will render the raylib draw calls first, so the DevUI is always on top
        DevUIDraw(&devUIState);
        ImVec2 vec2Zero = {0.0f, 0.0f};
        ImVec2 vec2One = {1.0f, 1.0f};
        ImVec4 vec4Zero = {0.0f, 0.0f, 0.0f, 0.0f};
        ImVec4 vec4One = {1.0f, 1.0f, 1.0f, 1.0f};
        ImVec2 size;
        size.x = santaTex.width / 4.0f;
        size.y = santaTex.height / 4.0f;
        if (igBegin("santa img", 0, 0 | ImGuiWindowFlags_AlwaysAutoResize))
            igImage((ImTextureID)santaTex.id, size, vec2Zero, vec2One, vec4One, vec4Zero);
        igEnd();

        DevUIRender();
        EndDrawing();
    }

    UnloadFont(fontRobotoMono);
    UnloadFont(fontRobotoMonoSm);
    UnloadFont(font);

    UnloadTexture(santaTex);

    DevUIDestroy(&devUIState);

    CloseWindow();

    return 0;
}