#ifndef __MAIN_H__
#define __MAIN_H__

#include <stdio.h>

//Generated by cmake using buildInfo.h.in template
#include "buildInfo.h"
#include "rayIncludes.h"

int main(void);

typedef char Fixed256String[255];

typedef struct UIState
{
    int dropdownBox000Active;
    bool dropDown000EditMode;

    int dropdownBox001Active;
    bool dropDown001EditMode;

    int spinner001Value;
    bool spinnerEditMode;

    int valueBox002Value;
    bool valueBoxEditMode;

    char textBoxText[64];
    bool textBoxEditMode;

    int listViewScrollIndex;
    int listViewActive;

    int listViewExScrollIndex;
    int listViewExActive;
    int listViewExFocus;
    Fixed256String listViewExList[8];

    char multiTextBoxText[141];
    bool multiTextBoxEditMode;
    Color colorPickerValue;

    int sliderValue;
    int sliderBarValue;
    float progressValue;

    bool forceSquaredChecked;

    float alphaValue;

    int comboBoxActive;

    int toggleGroupActive;

    Vector2 viewScroll;
    //----------------------------------------------------------------------------------

    // Custom GUI font loading
    Font font;

    bool exitWindow;
    bool showMessageBox;

    char textInput[256];
    bool showTextInputBox;

    char textInputFileName[256];
} UIState;

void initUI(UIState *state);
void drawUI(UIState *state);

#endif