#include "enttTest.h"
#include <imgui.h>
#include "rayIncludes.h"
#include "MetricsGui/include/metrics_gui/metrics_gui.h"
#include <ctime>

//Generated by cmake using buildInfo.h.in template
#include "buildInfo.h"
#define BLISS_FULL_HEADER BLISS_TITLE " " BLISS_VERSION
#include "DevUI.h"

#include "main.h"

int main()
{
    tryEntt();

   int screenWidth = 800;
   int screenHeight = 600;

    printf("Starting " BLISS_FULL_HEADER "...\n");
    InitWindow(screenWidth, screenHeight, BLISS_FULL_HEADER);

    Font fontRobotoMono = LoadFontEx("resources/fonts/RobotoMono-Regular.ttf", 28, nullptr, 255);
    Font fontRobotoMonoSm = LoadFontEx("resources/fonts/RobotoMono-Regular.ttf", 12, nullptr, 255);
    Font font = LoadFontEx("resources/fonts/Merriweather-Regular.ttf", 14, nullptr, 255);

//    SetTargetFPS(60);

    DevUIState devUIState;
    DevUIInit(&devUIState);

    Texture2D santaTex = LoadTexture("resources/santa/Idle (1).png");

    bool exitWindow = false;

    MetricsGuiMetric frameTimeMetric = MetricsGuiMetric();
    frameTimeMetric.mDescription = "Frame time";
    frameTimeMetric.mUnits = "s";
    frameTimeMetric.mFlags = MetricsGuiMetric::USE_SI_UNIT_PREFIX;
    MetricsGuiMetric inputTimeMetric = MetricsGuiMetric();
    inputTimeMetric.mDescription = "Input time";
    inputTimeMetric.mUnits = "s";
    inputTimeMetric.mFlags = MetricsGuiMetric::USE_SI_UNIT_PREFIX;
    MetricsGuiMetric simulationTimeMetric = MetricsGuiMetric();
    simulationTimeMetric.mDescription = "Simulation time";
    simulationTimeMetric.mUnits = "s";
    simulationTimeMetric.mFlags = MetricsGuiMetric::USE_SI_UNIT_PREFIX;
    MetricsGuiMetric renderTimeMetric = MetricsGuiMetric();
    renderTimeMetric.mDescription = "Render time";
    renderTimeMetric.mUnits = "s";
    renderTimeMetric.mFlags = MetricsGuiMetric::USE_SI_UNIT_PREFIX;
    MetricsGuiMetric devUiTimeMetric = MetricsGuiMetric();
    devUiTimeMetric.mDescription = "DevUI time";
    devUiTimeMetric.mUnits = "s";
    devUiTimeMetric.mFlags = MetricsGuiMetric::USE_SI_UNIT_PREFIX;

    MetricsGuiPlot plot;
    plot.AddMetric(&frameTimeMetric);
    plot.AddMetric(&inputTimeMetric);
    plot.AddMetric(&simulationTimeMetric);
    plot.AddMetric(&renderTimeMetric);
    plot.AddMetric(&devUiTimeMetric);
    plot.mBarRounding        = 0.f;    // amount of rounding on bars
    plot.mRangeDampening     = 0.95f;  // weight of historic range on axis range [0,1]
    plot.mInlinePlotRowCount = 2;      // height of DrawList() inline plots, in text rows
    plot.mPlotRowCount       = 5;      // height of DrawHistory() plots, in text rows
    plot.mVBarMinWidth       = 6;      // min width of bar graph bar in pixels
    plot.mVBarGapWidth       = 1;      // width of bar graph inter-bar gap in pixels
    plot.mShowAverage        = true;  // draw horizontal line at series average
    plot.mShowInlineGraphs   = false;  // show history plot in DrawList()
    plot.mShowOnlyIfSelected = false;  // draw show selected metrics
    plot.mShowLegendDesc     = true;   // show series description in legend
    plot.mShowLegendColor    = true;   // use series color in legend
    plot.mShowLegendUnits    = true;   // show units in legend values
    plot.mShowLegendAverage  = false;  // show series average in legend
    plot.mShowLegendMin      = true;   // show plot y-axis minimum in legend
    plot.mShowLegendMax      = true;   // show plot y-axis maximum in legend
    plot.mBarGraph           = false;  // use bars to draw history
    plot.mStacked            = false;  // stack series when drawing history
    plot.mSharedAxis         = false;  // use first series' axis range
    plot.mFilterHistory      = true;   // allow single plot point to represent more than on history value

    while (!exitWindow)
    {
        //Input
        //----------------------------------------------------------------------------------
        clock_t inputStart = clock();
        clock_t inputElapsed = 0;
        exitWindow = WindowShouldClose();

        if (!devUIState.igIO->WantCaptureMouse)
        {
            //only take mouse input in the game if imgui isn't catching it
            //clicks and input shouldn't go through a window
        }
        if (!devUIState.igIO->WantCaptureKeyboard)
        {
            //check keyboard inputs
        }
        if (!devUIState.igIO->WantTextInput)
        {
            //for on mobile & consoles
        }
        inputElapsed = (clock() - inputStart) / CLOCKS_PER_SEC;

        //Simulation
        //----------------------------------------------------------------------------------
        clock_t simulationStart = clock();
        clock_t simulationElapsed = 0;
        simulationElapsed = (clock() - simulationStart) / CLOCKS_PER_SEC;

        // Render
        //----------------------------------------------------------------------------------
        clock_t renderStart = clock();
        clock_t renderElapsed = 0;
        BeginDrawing();
        ClearBackground(WHITE);

        DrawTexture(santaTex,
                    screenWidth / 2 - santaTex.width / 2,
                    screenHeight / 2 - santaTex.height / 2, WHITE);

        Vector2 textDim = MeasureTextEx(fontRobotoMono, BLISS_FULL_HEADER,
                                        (float)fontRobotoMono.baseSize, 0);
        Vector2 textPos;
        textPos.x = ((float)screenWidth - textDim.x) / 2.0f;
        textPos.y = ((float)screenHeight - textDim.y) / 2.0f;

        DrawTextEx(fontRobotoMono, BLISS_FULL_HEADER, textPos,
                   (float)fontRobotoMono.baseSize, 0, DARKGRAY);
        renderElapsed = (clock() - renderStart) / CLOCKS_PER_SEC;

        //----------------------------------------------------------------------------------
        //Dev UI

        clock_t devUiStart = clock();
        clock_t devUiElapsed = 0;

        DevUINewFrame();
        DevUIDraw(&devUIState);
        ImGui::ShowDemoWindow(&devUIState.show_demo_window);

        ImVec2 vec2Zero = {0.0f, 0.0f};
        ImVec2 vec2One = {1.0f, 1.0f};
        ImVec4 vec4Zero = {0.0f, 0.0f, 0.0f, 0.0f};
        ImVec4 vec4One = {1.0f, 1.0f, 1.0f, 1.0f};
        ImVec2 size;
        size.x = (float)santaTex.width / 4.0f;
        size.y = (float)santaTex.height / 4.0f;
        if (ImGui::Begin("santa img", nullptr, 0)) {
//            ImGui::Image((ImTextureID) &santaTex, size, vec2Zero, vec2One, vec4One, vec4Zero);
            plot.DrawHistory();
            plot.DrawList();
        }
        ImGui::End();
        DevUIRender();
        devUiElapsed = (clock() - devUiStart) / CLOCKS_PER_SEC;

        //render timing is split so as to not include devui times
        renderStart = clock();
        EndDrawing();
        renderElapsed += (clock() - renderStart) / CLOCKS_PER_SEC;

        inputTimeMetric.AddNewValue(inputElapsed);
        simulationTimeMetric.AddNewValue(simulationElapsed);
        renderTimeMetric.AddNewValue(renderElapsed);
        devUiTimeMetric.AddNewValue(devUiElapsed);
        frameTimeMetric.AddNewValue(GetFrameTime());
        plot.UpdateAxes();
    }

    UnloadFont(fontRobotoMono);
    UnloadFont(fontRobotoMonoSm);
    UnloadFont(font);

    UnloadTexture(santaTex);

    DevUIDestroy(&devUIState);

    CloseWindow();
    return 0;
}