name: deploy

on:
  push:
    tags:
      - v*

jobs:

  conan:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
    - uses: docker://conanio/gcc8
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        version: 3.6
    - name: Install
      run: |
        chmod +x conan/ci/install.sh
        ./conan/ci/install.sh
    - name: Deploy
      env:
        CONAN_LOGIN_USERNAME: ${{ secrets.CONAN_LOGIN_USERNAME }}
        CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
        CONAN_UPLOAD: ${{ secrets.CONAN_UPLOAD }}
        CONAN_GCC_VERSIONS: 8
      run: |
        chmod +x conan/ci/build.sh
        ./conan/ci/build.sh
