#include "build_info.h" //Generated by cmake using buildInfo.h.in template

#include "bliss_app.h"
#include "log_router.h"
#include "perf_timer.h"

Bliss_App::Bliss_App()
{
    log_router_enable();
}

void Bliss_App::run()
{
    TraceLog(LOG_INFO, "Starting " BLISS_FULL_HEADER "...\n");
    InitWindow(screen_width, screen_height, BLISS_FULL_HEADER);

    dev_ui.init();

    TraceLog(LOG_INFO, "Loading fonts");
    load_fonts();

    TraceLog(LOG_INFO, "Loading textures");
    load_textures();

    // raylib set fps
    SetTargetFPS(144);

    TraceLog(LOG_INFO, "Starting simulation");
    while (!exit_window)
    {
        handle_input();
        simulation_step();
        draw_scene();
        draw_dev_ui();

        render_dev_ui();
        render_scene();

        //Update metrics plot
        dev_ui.plot.UpdateAxes();
    }

    CloseWindow();
}

void Bliss_App::render_dev_ui()
{
    Perf_Timer t(dev_ui.metrics.dev_ui_render_time);
    dev_ui.render();
}

void Bliss_App::render_scene()
{
    Perf_Timer t(dev_ui.metrics.drawing_time);
    EndDrawing();
}

void Bliss_App::draw_dev_ui()
{
    //----------------------------------------------------------------------------------
    //Dev UI
    Perf_Timer t(dev_ui.metrics.dev_ui_time);

    dev_ui.new_frame();
    dev_ui.draw();

    ImVec2 vec2_zero = { 0.0f, 0.0f };
    ImVec2 vec2_one  = { 1.0f, 1.0f };
    ImVec4 vec4_zero = { 0.0f, 0.0f, 0.0f, 0.0f };
    ImVec4 vec4_one  = { 1.0f, 1.0f, 1.0f, 1.0f };
    ImVec2 size;
    size.x = (float)santa_tex.width  / 4.0f;
    size.y = (float)santa_tex.height / 4.0f;
    if (ImGui::Begin("santa img", nullptr, 0))
    {
        ImGui::Image((ImTextureID)&santa_tex, size, vec2_zero, vec2_one, vec4_one, vec4_zero);
    }
    ImGui::End();

    log_gui.draw("Log");
}

void Bliss_App::draw_scene()
{
    // Draw prep
    //----------------------------------------------------------------------------------
    Perf_Timer t(dev_ui.metrics.draw_prep_time);
    BeginDrawing();

    ClearBackground(WHITE);

    DrawTexture(santa_tex,
        screen_width  / 2 - santa_tex.width  / 2,
        screen_height / 2 - santa_tex.height / 2, WHITE);

    Vector2 text_dim = MeasureTextEx(font_roboto_mono, BLISS_FULL_HEADER,
        (float)font_roboto_mono.baseSize, 0);
    Vector2 text_pos;
    text_pos.x = ((float)screen_width  - text_dim.x) / 2.0f;
    text_pos.y = ((float)screen_height - text_dim.y) / 2.0f;

    DrawTextEx(font_roboto_mono, BLISS_FULL_HEADER, text_pos,
        (float)font_roboto_mono.baseSize, 0, DARKGRAY);
}

void Bliss_App::simulation_step()
{
    //Simulation
    //----------------------------------------------------------------------------------
    Perf_Timer t(dev_ui.metrics.simulation_time);
    // simulate go here
}

void Bliss_App::handle_input()
{
    //Input handling
    //----------------------------------------------------------------------------------
    //Note: Input is actually polled inside raylib's EndDrawing (after frame
    //      waiting is finished! so effectively its as good as doing right
    //      before this point)
    Perf_Timer t(dev_ui.metrics.input_time);
    exit_window = WindowShouldClose();

    if (IsKeyPressed(KEY_E)) {
        TraceLog(LOG_INFO, "hi");
    }

    if (!dev_ui.ig_io->WantCaptureMouse)
    {
        //only take mouse input in the game if imgui isn't catching it
        //clicks and input shouldn't go through a window
    }
    if (!dev_ui.ig_io->WantCaptureKeyboard)
    {
        //check keyboard inputs
    }
    if (!dev_ui.ig_io->WantTextInput)
    {
        //for on mobile & consoles
    }
}

void Bliss_App::load_fonts() {
    font_roboto_mono =    LoadFontEx("resources/fonts/RobotoMono-Regular.ttf",   28, nullptr, 255);
    font_roboto_mono_sm = LoadFontEx("resources/fonts/RobotoMono-Regular.ttf",   12, nullptr, 255);
    font =                LoadFontEx("resources/fonts/Merriweather-Regular.ttf", 14, nullptr, 255);
}

void Bliss_App::load_textures() {
    santa_tex = LoadTexture("resources/santa/Idle (1).png");
}

Bliss_App::~Bliss_App()
{
    TraceLog(LOG_INFO, "Unloading fonts...");
    UnloadFont(font_roboto_mono);
    UnloadFont(font_roboto_mono_sm);
    UnloadFont(font);

    TraceLog(LOG_INFO, "Unloading textures...");
    UnloadTexture(santa_tex);
}
